apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model-name}-deployment
spec:
  selector:
    matchLabels:
      app: {model-name}-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {model-name}-server
    spec:
      containers:
      - name: {model-name}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{docker-user}/{model-name}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        ##
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model-name}-service
  name: {model-name}-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {model-name}-server
  type: LoadBalancer
